// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytgjphlhxrzsknbgqfws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0Z2pwaGxoeHJ6c2tuYmdxZndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTAxODAsImV4cCI6MjA2NTkyNjE4MH0.131boY4TN7hSN0br5kg1nrwZUSUFieezi3uGpEXCgAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});